package com.mycompany.bank.management.system;
import java.awt.Color;
import java.awt.event.KeyListener;
import javax.swing.JOptionPane;
import java.sql.*;
import java.lang.Math;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
/**
 *
 * @author deependra
 */

public class singup extends javax.swing.JFrame {

    public String username_1;

    public singup() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        labelstep1 = new javax.swing.JLabel();
        labelstep2 = new javax.swing.JLabel();
        labelstep3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        step2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        occupationchoice = new java.awt.Choice();
        jButton2 = new javax.swing.JButton();
        user_name = new javax.swing.JTextField();
        fathername = new javax.swing.JTextField();
        mothername = new javax.swing.JTextField();
        mobilenumber = new javax.swing.JTextField();
        emails = new javax.swing.JTextField();
        aadharno = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        phoneinvalid = new javax.swing.JLabel();
        step3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        cardname = new javax.swing.JTextField();
        cardaccountno = new javax.swing.JTextField();
        cardnumber = new javax.swing.JTextField();
        cardpin = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        choiceaccount = new java.awt.Choice();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        cardamount = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        message1 = new javax.swing.JLabel();
        step1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        usertextfield = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        passtextfield = new javax.swing.JTextField();
        repasstextfield = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1047, 746));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(51, 255, 51));

        labelstep1.setBackground(new java.awt.Color(255, 255, 255));
        labelstep1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelstep1.setForeground(new java.awt.Color(0, 0, 0));
        labelstep1.setText("              Step 1");
        labelstep1.setForeground(new java.awt.Color(0, 0, 0));
        labelstep1.setOpaque(true);

        labelstep2.setBackground(new java.awt.Color(0, 255, 255));
        labelstep2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelstep2.setForeground(new java.awt.Color(0, 0, 0));
        labelstep2.setText("              Step 2");
        labelstep2.setOpaque(true);

        labelstep3.setBackground(new java.awt.Color(0, 255, 255));
        labelstep3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelstep3.setForeground(new java.awt.Color(0, 0, 0));
        labelstep3.setText("              Step 3");
        labelstep3.setOpaque(true);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Priority Bank");

        jLabel25.setIcon(new javax.swing.ImageIcon("/home/deependra/CODE/JAVA/Bank-Management-System/Images/bank.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelstep1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelstep2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelstep3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(labelstep1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelstep2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelstep3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(238, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(153, 255, 255));

        step2.setBackground(new java.awt.Color(255, 255, 255));
        step2.setVisible(false);

        jLabel5.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("PERSONAL DETAILS");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Name");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Father's Name");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Mother's Name");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Mobile Number");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("E-mail");

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Aadhar Number");

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Occupation");

        occupationchoice.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        occupationchoice.add("Select");
        occupationchoice.add("Student");
        occupationchoice.add("Businessman");
        occupationchoice.add("Private");
        occupationchoice.add("Government");

        jButton2.setBackground(new java.awt.Color(255, 255, 153));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("NEXT");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        user_name.setBackground(new java.awt.Color(255, 255, 255));
        user_name.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        user_name.setForeground(new java.awt.Color(0, 0, 0));
        user_name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        fathername.setBackground(new java.awt.Color(255, 255, 255));
        fathername.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        fathername.setForeground(new java.awt.Color(0, 0, 0));
        fathername.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        mothername.setBackground(new java.awt.Color(255, 255, 255));
        mothername.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        mothername.setForeground(new java.awt.Color(0, 0, 0));
        mothername.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        mobilenumber.setBackground(new java.awt.Color(255, 255, 255));
        mobilenumber.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        mobilenumber.setForeground(new java.awt.Color(0, 0, 0));
        mobilenumber.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        mobilenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobilenumberActionPerformed(evt);
            }
        });
        mobilenumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mobilenumberKeyTyped(evt);
            }
        });

        emails.setBackground(new java.awt.Color(255, 255, 255));
        emails.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        emails.setForeground(new java.awt.Color(0, 0, 0));
        emails.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        aadharno.setBackground(new java.awt.Color(255, 255, 255));
        aadharno.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        aadharno.setForeground(new java.awt.Color(0, 0, 0));
        aadharno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel22.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Address");

        address.setBackground(new java.awt.Color(255, 255, 255));
        address.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        address.setForeground(new java.awt.Color(0, 0, 0));
        address.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel2.setIcon(new javax.swing.ImageIcon("/home/deependra/CODE/JAVA/Bank-Management-System/Images/profileimg.png")); // NOI18N

        phoneinvalid.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        phoneinvalid.setForeground(new java.awt.Color(255, 255, 255));
        phoneinvalid.setText("Invalid");

        javax.swing.GroupLayout step2Layout = new javax.swing.GroupLayout(step2);
        step2.setLayout(step2Layout);
        step2Layout.setHorizontalGroup(
            step2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(step2Layout.createSequentialGroup()
                .addGroup(step2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(step2Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(step2Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(user_name, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(step2Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(fathername, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(step2Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(mothername, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(step2Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(mobilenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(step2Layout.createSequentialGroup()
                        .addGap(393, 393, 393)
                        .addComponent(phoneinvalid, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(step2Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(emails, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(step2Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(aadharno, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(step2Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(occupationchoice, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(step2Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(step2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(step2Layout.createSequentialGroup()
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(91, 91, 91))
        );
        step2Layout.setVerticalGroup(
            step2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(step2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(step2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(step2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(step2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(step2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(user_name, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(step2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fathername, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(step2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mothername, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(step2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mobilenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(phoneinvalid, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(step2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emails, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(step2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aadharno, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(step2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(occupationchoice, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(step2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(step2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        step3.setBackground(new java.awt.Color(255, 255, 255));
        step3.setVisible(false);

        jLabel14.setFont(new java.awt.Font("Dialog", 3, 32)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("Card Details");

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Card Holder Name");

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Account Number");

        jButton3.setBackground(new java.awt.Color(255, 255, 153));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon("/home/deependra/CODE/JAVA/Bank-Management-System/Images/button.png")); // NOI18N
        jButton3.setText("SUBMIT");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cardname.setBackground(new java.awt.Color(255, 255, 255));
        cardname.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        cardname.setForeground(new java.awt.Color(0, 0, 0));

        cardaccountno.setBackground(new java.awt.Color(255, 255, 255));
        cardaccountno.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        cardaccountno.setForeground(new java.awt.Color(0, 0, 0));

        cardnumber.setBackground(new java.awt.Color(255, 255, 255));
        cardnumber.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        cardnumber.setForeground(new java.awt.Color(0, 0, 0));

        cardpin.setBackground(new java.awt.Color(255, 255, 255));
        cardpin.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        cardpin.setForeground(new java.awt.Color(0, 0, 0));
        cardpin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardpinActionPerformed(evt);
            }
        });
        cardpin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cardpinKeyTyped(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("PIN");

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Card Number");

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Account Type");

        choiceaccount.setBackground(new java.awt.Color(255, 255, 255));
        choiceaccount.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        choiceaccount.add("Select");
        choiceaccount.add("Saving Account");
        choiceaccount.add("Commercial Account");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jSeparator1.setOpaque(true);

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Ammount");

        cardamount.setBackground(new java.awt.Color(255, 255, 255));
        cardamount.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        cardamount.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setIcon(new javax.swing.ImageIcon("/home/deependra/CODE/JAVA/Bank-Management-System/Images/credit.png")); // NOI18N

        message1.setBackground(new java.awt.Color(255, 255, 255));
        message1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        message1.setForeground(new java.awt.Color(255, 0, 0));
        message1.setText("Only Numbers are allowed");
        message1.setVisible(false);

        javax.swing.GroupLayout step3Layout = new javax.swing.GroupLayout(step3);
        step3.setLayout(step3Layout);
        step3Layout.setHorizontalGroup(
            step3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(step3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(step3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(step3Layout.createSequentialGroup()
                        .addGroup(step3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(step3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(step3Layout.createSequentialGroup()
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cardamount, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, step3Layout.createSequentialGroup()
                                    .addGroup(step3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(100, 100, 100)
                                    .addGroup(step3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cardnumber)
                                        .addComponent(cardname)
                                        .addComponent(cardaccountno, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(cardpin, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, step3Layout.createSequentialGroup()
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(139, 139, 139)
                                    .addComponent(choiceaccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 159, Short.MAX_VALUE))
                    .addGroup(step3Layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(message1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(step3Layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addGroup(step3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        step3Layout.setVerticalGroup(
            step3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(step3Layout.createSequentialGroup()
                .addGroup(step3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(step3Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, step3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(step3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardname, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(step3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardaccountno, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(step3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(step3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardpin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(message1)
                .addGap(27, 27, 27)
                .addGroup(step3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(choiceaccount, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(step3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardamount, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        step1.setBackground(new java.awt.Color(255, 255, 255));
        step1.setVisible(true);

        jLabel8.setFont(new java.awt.Font("Dialog", 2, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("LOGIN DETAILS");

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("USERNAME");

        usertextfield.setBackground(new java.awt.Color(255, 255, 255));
        usertextfield.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        usertextfield.setForeground(new java.awt.Color(0, 0, 0));
        usertextfield.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("PASSWORD");

        jLabel20.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("RE-PASSWORD");

        passtextfield.setBackground(new java.awt.Color(255, 255, 255));
        passtextfield.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        passtextfield.setForeground(new java.awt.Color(0, 0, 0));
        passtextfield.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        repasstextfield.setBackground(new java.awt.Color(255, 255, 255));
        repasstextfield.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        repasstextfield.setForeground(new java.awt.Color(0, 0, 0));
        repasstextfield.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jButton1.setBackground(new java.awt.Color(255, 255, 102));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("NEXT");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/deependra/CODE/JAVA/Bank-Management-System/Images/key.png")); // NOI18N

        javax.swing.GroupLayout step1Layout = new javax.swing.GroupLayout(step1);
        step1.setLayout(step1Layout);
        step1Layout.setHorizontalGroup(
            step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(step1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20)))
                .addGap(110, 110, 110)
                .addGroup(step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usertextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(repasstextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(218, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, step1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(step1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(156, 156, 156))
        );
        step1Layout.setVerticalGroup(
            step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(step1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(145, 145, 145)
                .addGroup(step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usertextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(repasstextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(step1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(step2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(step3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(step1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(step2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(step3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String user,pass,repass;
        user=usertextfield.getText();
        boolean check=checkusername(user);
        if(check)
        {
            pass=passtextfield.getText();
            repass=repasstextfield.getText();
            if(pass.equals(repass))
            {
            if((user.length()>6 && pass.length()>6)&&((user.length()<=20 && pass.length()<=20)))
            {
                    username_1=user;
                    logindetails(user,pass);
                    step1.setVisible(false);
                    step2.setVisible(true);
                    labelstep1.setBackground(new java.awt.Color(0, 255, 255));
                    labelstep2.setBackground(new java.awt.Color(255, 255, 255));
                
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Username and Password should be greater than 6 and Less than 20 character ");
            }
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Password and Re-Password are not equal");
            }     
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Username Already exists");
        }   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        
        
        String name,father,mother,mobile,aadhar,occupation,email,address1;
        name=user_name.getText();
        father=fathername.getText();
        mother=mothername.getText();
        mobile=mobilenumber.getText();
        aadhar=aadharno.getText();
        email=emails.getText();
        occupation=occupationchoice.getSelectedItem();
        address1=address.getText();
        if((address1.length()==0)||(name.length()==0)||(father.length()==0)||(mother.length()==0)||(mobile.length()==0)||(aadhar.length()==0)||(email.length()==0)||(occupation.equals("Select")))
        {
            JOptionPane.showMessageDialog(this,"All field are required");
        }
        else
        {
            if((mobile.length()==10)&&(aadhar.length()==12))
            {
                if(email.contains("@"))
                {
                    personaldetails(username_1,name,father,mother,mobile,aadhar,email,occupation,address1);
                    step1.setVisible(false);
                    step2.setVisible(false);
                    step3.setVisible(true);
                    labelstep2.setBackground(new java.awt.Color(0, 255, 255));
                    labelstep3.setBackground(new java.awt.Color(255, 255, 255));
                    int t=1;
                    while(t!=0)
                    {
                        long a=(long)(Math.random()*Math.pow(10, 16));
                        long b=(long)(Math.random()*Math.pow(10, 12));
                        String accountno01=Long.toString(a);
                        String cardno02=Long.toString(b);
                        if((accountno01.length()==15)&&(cardno02.length()==12))
                        {
                            cardaccountno.setText(accountno01);
                            cardnumber.setText(cardno02);
                            t=0;
                            break;
                        }      
                    }
                     
                    
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"E-mails are not valid!!!");
                }             
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Mobile Number or Aadhar Number are not valid!!!");
            }
          
        }
     
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cardpinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardpinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardpinActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String cardholder,pin,coiceaccount,accountno1,cardno1,amount,ifsc="",accountstatus="ACTIVATE",cvv="";
        cardholder=cardname.getText();
        pin=cardpin.getText();
        coiceaccount=choiceaccount.getSelectedItem();
        accountno1=cardaccountno.getText();
        cardno1=cardnumber.getText();
        amount=cardamount.getText();
        int t1=1;
        while(t1!=0)
        {
            int a=(int)(Math.random()*Math.pow(10,6));
            String ab=Integer.toString(a);
            if(ab.length()==6)
            {
                ifsc="PRTY"+ab;
                t1=0;
                break;
            }
        }
        int t2=1;
        while(t2!=0)
        {
            int b=(int)(Math.random()*Math.pow(10,3));
            String abc=Integer.toString(b);
            if(abc.length()==3)
            {
                cvv=abc;
                t2=0;
                break;
            }
        }
        
        
        
        if(pin.length()==4)
        {
            
            carddetails(username_1,cardholder,pin,coiceaccount,accountno1,cardno1,amount,ifsc,accountstatus,cvv);
            login l=new login();
            l.setVisible(true);
            dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(this,"PIN is Invalid");
        }
   
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cardpinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cardpinKeyTyped
        // TODO add your handling code here:
        
        char c=evt.getKeyChar();
        if((Character.isDigit(c)) || (c==KeyEvent.VK_BACK_SPACE))
        {
            message1.setVisible(false);
             if(cardpin.getText().length()<=3)
            {
            
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Only 4 digit allowed");
                cardpin.removeKeyListener((KeyListener) this);
            
            }
        }
        else
        {
            evt.consume();
            message1.setVisible(true);
        }
        
        
        
        
       
    }//GEN-LAST:event_cardpinKeyTyped

    private void mobilenumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobilenumberKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if((Character.isDigit(c)) || (c==KeyEvent.VK_BACK_SPACE))
        {
            phoneinvalid.setForeground(Color.white);
            phoneinvalid.setText("Incorrect");
            if(mobilenumber.getText().length()==10)
            {
                phoneinvalid.setText("Correct");
                phoneinvalid.setForeground(Color.GREEN);
                phoneinvalid.setVisible(true);
                mobilenumber.removeKeyListener((KeyListener) this);
                
            }
            else
            {
                phoneinvalid.setText("Invalid");
                phoneinvalid.setForeground(Color.white);
//                phoneinvalid.removeKeyListener((KeyListener) this);
            
            }
        }
        else
        {
            evt.consume();
            phoneinvalid.setText("Invalid");
            phoneinvalid.setForeground(Color.red);
        }
        
    }//GEN-LAST:event_mobilenumberKeyTyped

    private void mobilenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobilenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobilenumberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(singup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(singup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(singup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(singup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new singup().setVisible(true);
            }
        });     
        
    }
    // ********************* THread ******************************/
    
    
    
    
    public static void logindetails(String user,String pass1)
    {
        String query1="insert into logindetails(username,pass) values(?,?);";
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con1=DriverManager.getConnection("jdbc:mysql://127.0.0.1/bankdata","root","deependra");
            PreparedStatement ps1=con1.prepareStatement(query1);
            ps1.setString(1,user);
            ps1.setString(2, pass1);
            ps1.executeUpdate();
            con1.close();
            
        }
        catch(SQLException | ClassNotFoundException e)
        {
            System.out.println("Error");
        }
    }
    
    // ************************* personal details ****************************/
    public static void personaldetails(String user,String name,String father,String mother,String mobile,String email,String aadhar,String occupation,String address)
    {
        String query="insert into personaldetails values(?,?,?,?,?,?,?,?,?);";
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con2=DriverManager.getConnection("jdbc:mysql://127.0.0.1/bankdata","root","deependra");
            PreparedStatement ps=con2.prepareStatement(query);
            ps.setString(1,user);
            ps.setString(2,name);
            ps.setString(3,father);
            ps.setString(4,mother);
            ps.setString(5,mobile);
            ps.setString(7,email);
            ps.setString(6,aadhar);
            ps.setString(8,occupation);
            ps.setString(9, address);
            ps.executeUpdate();
            con2.close();
        }
        catch(SQLException | ClassNotFoundException e)
        {
            System.out.println("error");
        }
    }
    
    // ********************** card details **************************/
    public static void carddetails(String username,String holdername,String pin,String choiceaccount,String accountno,String cardno,String amount,String IFSC,String accstatus,String cvv)
    {
        String query="insert into carddetails values(?,?,?,?,?,?,?,?,?,?);";
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con3=DriverManager.getConnection("jdbc:mysql://127.0.0.1/bankdata","root","deependra");
            PreparedStatement ps=con3.prepareStatement(query);
            ps.setString(1,username);
            ps.setString(2,holdername);
            ps.setString(3,accountno);
            ps.setString(4, cardno);
            ps.setString(5,pin);
            ps.setString(6,choiceaccount);
            ps.setString(7,amount);
            ps.setString(8,IFSC);
            ps.setString(9,accstatus);
            ps.setString(10,cvv);
            ps.executeUpdate();
            con3.close();
            
        }
        catch(ClassNotFoundException | SQLException e)
        {
            System.out.println("error");
        }
        
        
    }
    /*********************** Check username *****************************************/
    public static boolean checkusername(String username)
    {
        
        int t1=0;
        String query="select username from logindetails;";
        try
        {
            Class.forName("com.mysql.jdbc.Driver");         
            Connection con4=DriverManager.getConnection("jdbc:mysql://127.0.0.1/bankdata","root","deependra");
            Statement s=con4.createStatement();
            ResultSet rs=s.executeQuery(query);
            while(rs.next())
            {
                String username1=rs.getString(1);
                if(username1.equals(username))
                {
                    t1=1;
                    break;
                }
                else
                {
                    t1=0;
                    
                }
            }
            con4.close();
            
        }
        catch(SQLException |ClassNotFoundException e)
        {
            System.out.print("error");
        }
        if(t1==1)
        {
            return false;
        }
        else
        {
            return true;
        }
      
        
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aadharno;
    private javax.swing.JTextField address;
    private javax.swing.JTextField cardaccountno;
    private javax.swing.JTextField cardamount;
    private javax.swing.JTextField cardname;
    private javax.swing.JTextField cardnumber;
    private javax.swing.JTextField cardpin;
    private java.awt.Choice choiceaccount;
    private javax.swing.JTextField emails;
    private javax.swing.JTextField fathername;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelstep1;
    private javax.swing.JLabel labelstep2;
    private javax.swing.JLabel labelstep3;
    private javax.swing.JLabel message1;
    private javax.swing.JTextField mobilenumber;
    private javax.swing.JTextField mothername;
    private java.awt.Choice occupationchoice;
    private javax.swing.JTextField passtextfield;
    private javax.swing.JLabel phoneinvalid;
    private javax.swing.JTextField repasstextfield;
    private javax.swing.JPanel step1;
    private javax.swing.JPanel step2;
    private javax.swing.JPanel step3;
    private javax.swing.JTextField user_name;
    private javax.swing.JTextField usertextfield;
    // End of variables declaration//GEN-END:variables
}
